<!--====================  hero slider area ====================-->

<div class="hero-slider-area section-space">
    <!-- START REVOLUTION SLIDER 5.4.7 fullwidth mode -->
    <div id="rev_slider_23_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.4.7">
        <ul>
            <!-- SLIDE  -->
            <li data-index="rs-53" data-transition="slideoverdown,slidingoverlayvertical,cube-horizontal,3dcurtain-vertical" data-slotamount="default,default,default,default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default,default,default,default" data-easeout="default,default,default,default" data-masterspeed="980,default,default,default" data-thumb="" data-delay="7010" data-rotate="0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{asset('client/img/revimages/homepage01-slide1.jpg')}}" alt="" width="1920" height="1080" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption   tp-resizeme" id="slide-53-layer-5" data-x="['left','center','center','center']" data-hoffset="['1111','203','127','68']" data-y="['top','middle','middle','middle']" data-voffset="['242','-58','-16','-25']" data-fontsize="['80','90','90','60']" data-lineheight="['80','100','100','70']" data-width="none" data-height="['170','none','none','none']" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":770,"speed":1850,"frame":"0","from":"x:[175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;","mask":"x:[-100%];y:0;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power2.easeInOut"}]' data-textAlign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; max-width: 170px; max-width: 170px; white-space: nowrap; font-size: 80px; line-height: 80px; font-weight: 300; color: #000000; letter-spacing: -2px;font-family:Source Sans Pro;">Beautiful<br>
    Craftmanship </div>

                    <!-- LAYER NR. 2 -->
                    <a class="tp-caption Robin-Button-New rev-btn " href="shop-left-sidebar.html" target="_self" id="slide-53-layer-7" data-x="['left','center','center','center']" data-hoffset="['1257','209','135','68']" data-y="['top','middle','top','top']" data-voffset="['445','123','612','440']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions='' data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":770,"speed":1500,"frame":"0","from":"x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;","mask":"x:[100%];y:0;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"nothing"},{"frame":"hover","speed":"300","ease":"Power0.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(34,34,34);bc:rgb(0,0,0);"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[12,12,12,12]" data-paddingright="[25,25,25,25]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[25,25,25,25]" style="z-index: 6; white-space: nowrap; font-size: 16px; line-height: 21px; font-weight: 700; color: #000000; font-family:Source Sans Pro;background-color:rgba(247,177,19,0);border-color:rgba(0,0,0,1);border-style:solid;border-width:2px 2px 2px 2px;border-radius:5px 5px 5px 5px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none;">SHOP NOW!
                    </a>
            </li>
            <!-- SLIDE  -->
            <li data-index="rs-54" data-transition="parallaxtoright,parallaxtoleft,parallaxtotop,parallaxtobottom,parallaxhorizontal,slidingoverlaydown,slidingoverlayleft,slidingoverlayright,slidingoverlayhorizontal" data-slotamount="default,default,default,default,default,default,default,default,default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default,default,default,default,default,default,default,default,default" data-easeout="default,default,default,default,default,default,default,default,default" data-masterspeed="1000,default,default,default,default,default,default,default,default" data-thumb="" data-delay="7000" data-rotate="0,0,0,0,0,0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{asset('client/img/revimages/homepage01-slide2.jpg')}}" alt="" width="1920" height="1080" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 3 -->
                <div class="tp-caption   tp-resizeme" id="slide-54-layer-5" data-x="['left','center','center','center']" data-hoffset="['1078','243','156','43']" data-y="['top','top','top','top']" data-voffset="['252','153','104','64']" data-fontsize="['80','80','70','60']" data-lineheight="['80','80','70','60']" data-width="['468','none','none','none']" data-height="['161','none','none','none']" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":450,"speed":2000,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Back.easeIn"}]' data-textAlign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; min-width: 468px; max-width: 468px; max-width: 161px; max-width: 161px; white-space: nowrap; font-size: 80px; line-height: 80px; font-weight: 300; color: #000000; letter-spacing: -2px;font-family:Source Sans Pro;">Furniture<br>
    New Colection </div>

                    <!-- LAYER NR. 4 -->
                    <a class="tp-caption Robin-Button-New rev-btn " href="shop-left-sidebar.html" target="_self" id="slide-54-layer-7" data-x="['left','center','center','center']" data-hoffset="['1248','249','164','46']" data-y="['top','middle','top','top']" data-voffset="['480','4','308','226']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions='' data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":1080,"speed":940,"frame":"0","from":"y:-50px;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power2.easeInOut"},{"frame":"hover","speed":"400","ease":"Power4.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(34,34,34);bc:rgb(0,0,0);"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[12,12,12,12]" data-paddingright="[25,25,25,25]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[25,25,25,25]" style="z-index: 6; white-space: nowrap; font-size: 16px; line-height: 21px; font-weight: 700; color: #000000; font-family:Source Sans Pro;background-color:rgba(247,177,19,0);border-color:rgba(0,0,0,1);border-style:solid;border-width:2px 2px 2px 2px;border-radius:5px 5px 5px 5px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none;">SHOP NOW!
                    </a>
            </li>
            <!-- SLIDE  -->
            <li data-index="rs-55" data-transition="slidingoverlayhorizontal,fadetoleftfadefromright,fadetotopfadefrombottom,fadetorightfadefromleft,fadetobottomfadefromtop,curtain-2,curtain-1,curtain-3" data-slotamount="default,default,default,default,default,default,default,default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default,default,default,default,default,default,default,default" data-easeout="default,default,default,default,default,default,default,default" data-masterspeed="1000,default,default,default,default,default,default,default" data-thumb="" data-delay="6990" data-rotate="0,0,0,0,0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{asset('client/img/revimages/homepage01-slide3.jpg')}}" alt="" width="1920" height="1080" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 5 -->
                <div class="tp-caption   tp-resizeme" id="slide-55-layer-5" data-x="['left','center','center','left']" data-hoffset="['1102','205','119','209']" data-y="['top','top','top','top']" data-voffset="['253','97','144','134']" data-fontsize="['80','90','80','50']" data-lineheight="['80','90','80','60']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":600,"speed":1500,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power2.easeOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; white-space: nowrap; font-size: 80px; line-height: 80px; font-weight: 300; color: #000000; letter-spacing: -2px;font-family:Source Sans Pro;">Green up<br> your Lifestyle </div>

                    <!-- LAYER NR. 6 -->
                    <a class="tp-caption Robin-Button-New rev-btn " href="shop-left-sidebar.html" target="_self" id="slide-55-layer-7" data-x="['left','center','center','left']" data-hoffset="['1226','211','125','259']" data-y="['top','middle','top','top']" data-voffset="['462','-20','372','290']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions='' data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":520,"speed":1330,"frame":"0","from":"y:-50px;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"nothing"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(34,34,34);bc:rgb(0,0,0);"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[12,12,12,12]" data-paddingright="[25,25,25,25]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[25,25,25,25]" style="z-index: 6; white-space: nowrap; font-size: 16px; line-height: 21px; font-weight: 700; color: #000000; font-family:Source Sans Pro;background-color:rgba(247,177,19,0);border-color:rgba(0,0,0,1);border-style:solid;border-width:2px 2px 2px 2px;border-radius:5px 5px 5px 5px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none;">SHOP NOW!
                    </a>
            </li>
        </ul>
        <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>
    </div>
</div>


<!--====================  End of hero slider area  ====================-->